#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
from bpy.props import FloatProperty, IntProperty, StringProperty, BoolProperty, EnumProperty, PointerProperty
from . import utils
from . import panels
from . import constants as const
from . import temp


from bpy.app.translations import pgettext_iface as _ #For Translation of Text Required


def shape_callback(self,context):
    #print(f"Shape: {self.shape}")
    #if self.shape == "HEXAGON INNER TEXT" or self.shape == "HEXAGON OUTER TEXT" or self.shape =="OCTAGON OUTER TEXT" or self.shape == "HEXAGON FRONT TEXT":
    #    try:
    #        bpy.utils.register_class(panels.TP3D_P_Shapes)
    #    except:
    #        pass
    #else:
    #    try:
    #        bpy.utils.unregister_class(panels.TP3D_P_Shapes)
    #    except:
    #        pass
    pass

def generation_mode_update(self, context):
    self.use_multi_generation = (self.generation_mode == 'MULTI')

    
# Define a Property Group to store variables
class TP3D_Properties(bpy.types.PropertyGroup):
    file_path: StringProperty(
        name= _("File Path"),
        description= _("Select a file"),
        default="",
        maxlen=1024,
        subtype='FILE_PATH'  # Enables file selection
    )# type: ignore
    export_path: StringProperty(
        name= _("Export Path"),
        description= _("Where to save the STL file"),
        default="",
        maxlen=1024,
        subtype='DIR_PATH'  # Enables folder selection
    )# type: ignore
    chain_path: StringProperty(
        name= _("Folder Path"),
        description= _("Select a folder that contains multiple GPX files"),
        default="",
        maxlen=1024,
        subtype='DIR_PATH'  # Enables folder selection
    )# type: ignore
    trailName: StringProperty(name= _("Name"), default="", description="Leave empty to use the Filename") # type: ignore
    
    shape: EnumProperty(
        name = "Shape",
        items=[
            ("HEXAGON", _("Hexagon"), _("Hexagonal map")),
            ("SQUARE", _("Rectangle"), _("Rectangular map")),
            ("CIRCLE", _("Circle"), _("Circular map")),
            ("OCTAGON", _("Octagon"), _("Octagon Map")), #Premium
            ("ELLIPSE", _("Ellipse"), _("Ellipse Map")), #Premium
            ("HEART", _("Heart"), _("Heart Map")), #Premium
            ("HEXAGON INNER TEXT", _("Hexagon inner text"), _("Hexagonal map with inserted Text")),
            ("HEXAGON OUTER TEXT", _("Hexagon outer text"), _("Hexagonal map with backplate and text")),
            ("HEXAGON FRONT TEXT", _("Hexagon front text"), _("Hexagonal map with backplate and text on the front")),
            ("OCTAGON OUTER TEXT", _("Octagon outer text"), _("Octagon map with backplate and text"))
            #("MEDAL", _("Medal"), _("Circular medal with lower plate and curved text"))
        ],
        default = "HEXAGON",
        #update = shape_callback #calls shape_callback when user selects diffrent shape to register the Shape Panel
    )# type: ignore
    
    api: bpy.props.EnumProperty(
        name = "api",
        items=[
            ("OPENTOPODATA", "Opentopodata", _("Slower but more accurate elevation")),
            ("OPEN-ELEVATION","Open-Elevation",_("Faster but some regions are low quality")),
            ("TERRAIN-TILES", "Terrain-Tiles", _("Currently Fastest available set")),
            ("OPENTOPOGRAPHY", "OpenTopography", _("OpenTopography Global DEM API — requires API key for most datasets"))
        ],
        default = "TERRAIN-TILES"
    )# type: ignore

    openTopographyDataset: bpy.props.EnumProperty(
        name=_("Dataset"),
        items=[
            ("SRTMGL1",   "SRTM GL1 (30m)",    _("Global SRTM 30m resolution")),
            ("SRTMGL3",   "SRTM GL3 (90m)",    _("Global SRTM 90m resolution")),
            ("SRTM15Plus","SRTM15+ (500m)",     _("Global SRTM15+ 500m resolution — fastest download")),
            ("AW3D30",    "ALOS AW3D30 (30m)", _("Global ALOS World 3D 30m")),
            ("NASADEM",   "NASADEM (30m)",      _("NASA Digital Elevation Model 30m")),
            ("COP30",     "Copernicus 30m",     _("Copernicus DEM 30m")),
            ("COP90",     "Copernicus 90m",     _("Copernicus DEM 90m")),
        ],
        default="SRTMGL1"
    )# type: ignore

    apiRetries: IntProperty(name= _("Overpass API reuqest retries"), default = 5, min = 1, max = 20,description = _("How many Retries per Request before canceling")) # type: ignore

    dataset: EnumProperty(
        name = "Dataset",
        items=[
            ("srtm30m", "srtm30m", "Latitudes -60 to 60"),
            ("aster30m","aster30m","global"),
            ("ned10m","ned10m","Continental USA, Hawaii, parts of Alaska"),
            ("mapzen","mapzen","global"),
            ("nzdem8m","nzdem8m","New Zealand 8m"),
            ("eudem25m","eudem25m","Europe")
        ],
        default = "aster30m"
    )# type: ignore

    scalemode: EnumProperty(
        name= _("scalemode"),
        items=[
            ('FACTOR', _("Map Scale"), _("Set a scale based on the Map size")),
            ('COORDINATES', _("Coordinates"), _("Calculate the scale by using 2 Coordinates (Lat/lon)")),
            ('SCALE', _("Global Scale"), _("Set a scale based on the Global Scale (Mercator Projection)"))
        ],
        default='FACTOR'
    )# type: ignore
    pathScale: FloatProperty(name = _("Path Scale"), default = 0.8, min = 0.01, max = 200, description = _("Scale of Path in Relation to the Mapsize/GlobalScale (depending on scalemode)"))
    scaleLon1: FloatProperty(name = "Lon1", default = 0, description = _("The Longitude of the first coordinate"))
    scaleLat1: FloatProperty(name = "Lat1", default = 0, description = _("The Latitude of the first coordinate"))
    scaleLon2: FloatProperty(name = "Lon2", default = 0, description = _("The Longitude of the second coordinate"))
    scaleLat2: FloatProperty(name = "Lat2", default = 0, description = _("The Latitude of the second coordinate"))

    selfHosted: StringProperty(name = _("Self Hosted API"), default="", description= _("Has to be same API format as Opentopodata.org (https://api.opentopodata.org/v1/)"))

    objSize: IntProperty(name= _("Object Size in mm"), default = 100, min = 5, max = 10000,description = _("Size of the map in mm"))
    num_subdivisions: IntProperty(name = _("Resolution"), default = 4, min = 1, max = 10, description = _("(max recommended 8) Higher Number = more detailed terrain but slower generation"))
    scaleElevation: FloatProperty(name = _("Elevation Scale"), default = 10, min = 0, max = 10000, description = _("Multiplier to the Elevation"))
    pathThickness: FloatProperty(name = _("Path Thickness"), default = 1.2, min = 0.1, max = 5, description = _("Thickness of the path in mm"))
    shapeRotation: IntProperty(name = _("ShapeRotation"), default = 0, min = -360, max = 360, description = _("Rotation of the shape") )
    overwritePathElevation: BoolProperty(name= _("Overwrite Path Elevation"), default=True, description = _("Cast each point of the trail onto the Terrain Mesh"))
    o_verticesPath: StringProperty(name="Path vertices ", default="")
    o_verticesMap: StringProperty(name="Path Map ", default="")
    o_mapScale: StringProperty(name="Map Scale", default = "")
    o_time: StringProperty(name="TimeTook",default="")
    o_apiCounter_OpenTopoData: StringProperty(name="apiCounter_OpenTopodata", default = "API Limit: ---/1000 daily")
    o_apiCounter_OpenElevation: StringProperty(name="apiCounter_OpenElevation", default = "API Limit: ---/1000 monthly")
    o_centerx: FloatProperty(name = _("Center X"), default = 0, description = _("X Center of the Path"))
    o_centery: FloatProperty(name = _("Center Y"), default = 0, description = _("y Center of the Path"))

    magnetHeight: FloatProperty(name = _("Magnet Height"), default = 2.5, description = _("Height of the Holes for Magnets"))
    magnetDiameter: FloatProperty(name = _("Magnet Diameter"), default = 6.3, description = _("Diameter of the Holes for Magnets"))

    bottomMarkCutout: BoolProperty(name=_("Bottom Mark Cutout"), default = False, description = _("Creates Bottom mark as a Cutout"))

    ellipseRatio: FloatProperty(name = _("Ellipse Aspect Ratio"), default = 0.75, description = _("0.75 means the ellipse height is 0.75 x objSize"))
    rectangleHeight: IntProperty(name = _("Rectangle Height"), default = 100, description = _("Height of the Rectangle"))

    textFont: StringProperty(
        name= _("Font"),
        description=_("Select a file"),
        default="",
        maxlen=1024,
        subtype='FILE_PATH'  # Enables file selection
    )# type: ignore
    textSize: IntProperty(name= _("Text Size"), default = 5, min = 0, max = 1000) # type: ignore
    textSizeTitle: IntProperty(name= _("Title Text Size"), default = 0, min = 0, max = 1000, description = _("Keep 0 to use value from 'Text Size'")) # type: ignore
    titlefield: StringProperty(name= _("title"), default= "{name}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed}")) # type: ignore
    textfield1: StringProperty(name= _("text1"), default = "{length}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed}")) # type: ignore
    textfield2: StringProperty(name= _("text2"), default = "{elevation}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed}")) # type: ignore
    textfield3: StringProperty(name= _("text3"), default = "{duration}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed}")) # type: ignore
    titleIcon: EnumProperty(
        name="Title Icon",
        items=[
            ('cycling', _("Cycling Icon"), _("Cycling Icon before the Title")),
            ('hiking', _("Hiking Icon"), _("Hiking Icon before the Title")),
            ('running', _("Running Icon"), _("Running Icon before the Title")),
            ('swimming', _("Swimming Icon"), _("Swimming Icon before the Title")),
            ('skiing', _("Skiing Icon"), _("Skiing Icon before the Title")),
            ('snowboarding', _("Snowboarding Icon"), _("Snowboarding Icon before the Title")),
            ('kajak', _("Kayak Icon"), _("Kayak Icon before the Title")),
            ('no', _("No Icon"), _("No icon before the Title"))
        ],
        default='no'
    )# type: ignore
    iconText1: EnumProperty(
        name="Text 1Icon",
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='distance'
    )# type: ignore
    iconText2: EnumProperty(
        name="Text 2 Icon",
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='elevation'
    )# type: ignore
    iconText3: EnumProperty(
        name="Text 3 Icon",
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='time'
    )# type: ignore

    svg_path: StringProperty(
        name= _("SVG Path"),
        description= _("Select a .SVG file"),
        default="",
        maxlen=1024,
        subtype='FILE_PATH'  # Enables file selection
    )# type: ignore

    #overwriteLength: StringProperty(name= _("text1"), default = "")
    #overwriteHeight: StringProperty(name= _("text2"), default = "")
    #overwriteTime: StringProperty(name= _("text3"), default = "")


    


    outerBorderSize: IntProperty(name= _("BorderSize in %"), default = 20, min = 0, max = 1000, description= _("Only for Shapes with Plate"))
    text_angle_preset: IntProperty(name= _("Text Angle"), description= _("Rotate Text on Shape"), default=0, min = 0, max = 260)
    plateThickness: FloatProperty(name= _("plateThickness"), default = 5, description= _("Thickness of the Additional Plate"))
    plateInsertValue: FloatProperty(name= _("plateInsertValue"), default = 0, description= _("Depth of Cutout for the Map in the Plate, 0  to ignore"))
    plateBevel: FloatProperty(name= _("Plate Bevel"), default = 0.0, min = 0.0, max = 50.0, description= _("Bevel the top and bottom edges of the plate (0 to disable)"))

    tileSpacing: FloatProperty(name= _("tileSpacing"), default = 0, description= _("Distance between Tiles when Extending"))



    minThickness: FloatProperty(name= _("minThickness"), default = 2, min = 0.5, max = 1000, description= _("Additional Thickness on lowest point"))
    xTerrainOffset: FloatProperty(name= _("xTerrainOffset"), default = 0, description= _("Gives the map an Offset in X-Direction from the path"))
    yTerrainOffset: FloatProperty(name= _("yTerrainOffset"), default = 0, description= _("Gives the map an Offset in Y-Direction from the path"))

    rescaleMultiplier: FloatProperty(name = _("scale"), default = 1, min = 0, max = 10000)
    thickenValue: FloatProperty(name= _("thickenValue"), default = 1, description = _("Makes your Map 1mm thicker"))
    fixedElevationScale: BoolProperty(name= _("FixedElevationScale(10mm)"), default=False, description = _("Force the elevation to be 10mm High from highest to lowest point (ElevationScale still applies after that)"))
    singleColorMode: BoolProperty(name= _("SingleColorMode Trail"), default = False, description = _("Enable this if you don't have a Multicolor printer"))
    tolerance: FloatProperty(name= _("SingleColorMode Tolerance"), default = 0.2, description="Tolerance of the Trail for the SingleColorMode")
    toleranceElements: FloatProperty(name= _("ToleranceElements"), default = 0.4, description= _("Tolerance of the Elements (Water, Forest) for the SingleColorMode"))
    disableCache: BoolProperty(name= _("disableCache"), default = False, description = _("Disable cache if you encounter random holes in your mesh"))
    ccacheSize: IntProperty(name = _("Cache Size"), default = 50000, min = 0)
    indipendendTiles : BoolProperty(name= _("IndipendendTiles"), default = False, description = _("Tile minThickness is independent from other tiles"))

    elementMode: EnumProperty(
        name="Element handling",
        items=[
            ('PAINT', _("Paint on Map"), "Paint the Elements onto the map"),
            ('SINGLECOLORMODE_REMESH', _("Single-Color mode"), "Use this SingleColorMode, if it causes problems try the other one"),
            #('SINGLECOLORMODE', _("SingleColor (Alternative)"), "Use this SingleColorMode if the other one causes problems"),
            ('SEPARATE', _("Separate objects"), "Elements as separate objects (Increase Element Threshold to filter out unprintable element 'noise')")
        ],
        default='PAINT'
    )# type: ignore
    elementModeInset: FloatProperty(name=_("Clip Inset"), default=2.0, min=0.0, description=_("Thickness of solid frame for SCM-elements"))# type: ignore


    col_wArea: FloatProperty(name= _("Water Threshold"), default = 1, description = _("Lakes smaller than the threshold won't be included"))
    col_wStreamWidth: FloatProperty(name= _("River Width"), default = 1.0, min=0.1, max=10.0, description = _("Adjusts the thickness of rivers and streams"))
    col_wPondsActive: BoolProperty(name= _("Ponds & Lakes"), default=False, description = _("Include ponds and lakes (natural=water)"))
    col_wSmallRiversActive: BoolProperty(name= _("Small Rivers"), default=False, description = _("Streams, canals, ditches and other minor waterways"))
    col_wBigRiversActive: BoolProperty(name= _("Big Rivers"), default=False, description = _("Major named rivers (waterway with wikidata tag)"))
    col_fActive: BoolProperty(name= _("Include Forests"), default=False, description = _("For Maps < 50Km Recommended"))
    col_fArea: FloatProperty(name= _("Threshold"), default = 10, description = _("Forests smaller than the threshold won't be included"))
    col_scrActive: BoolProperty(name= _("Include Scree"), default=False, description = _("Rocky/stony terrain. For Maps < 1000Km Recommended"))
    col_scrArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Scree patches smaller than the threshold won't be included"))
    col_cActive: BoolProperty(name= _("Include City Boundaries"), default=False, description = _("For Maps < 100Km Recommended"))
    col_cArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Cities smaller than the threshold won't be included"))
    col_grActive: BoolProperty(name= _("Include Greenspaces"), default=False, description = _("Parks, gardens, grass and other urban green areas. For Maps < 100Km Recommended"))
    col_grArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Greenspaces smaller than the threshold won't be included"))
    col_faActive: BoolProperty(name= _("Include Farmland"), default=False, description = _("Fetches landuse=farmland and landuse=farmyard. For Maps < 1000Km Recommended"))
    col_faArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Farmland patches smaller than the threshold won't be included"))
    col_glActive: BoolProperty(name= _("Include Glaciers"), default=False, description = _("For Maps < 1000Km Recommended"))
    col_glArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Glaciers smaller than the threshold won't be included"))
    col_KeepManifold: BoolProperty(name= _("Keep Non-Manifold Objects"), default=False, description = _("Keep Broken/Non-Manifold objects"))
    el_bActive: BoolProperty(name= _("Include Buildings"), default=False, description = _("For Maps < 5Km Reccomended"))
    el_bHeightMultiplier: FloatProperty(name= _("Height Multiplier"), default=1.0, min=0.01, soft_max=10.0, description=_("Multiplies building height"))

    el_sMultiplier: FloatProperty(name= _("Street Width Multiplier"), default = 1, description = _("To make Streets thicker or thinner"))

    show_water: BoolProperty(name= _("Water & Ocean"), default=False)
    show_roads: BoolProperty(name= _("Roads"), default=False)
    el_sBigActive: BoolProperty(name= _("Big Streets"), default=False, description = f"primary, motorway, primary_link, motorway_link — limited to motorway only on maps < {const.ROADS_MAXSIZE}km")
    el_sMedActive: BoolProperty(name= _("Medium Streets"), default=False, description = f"secondary, tertiary, secondary_link, tertiary_link — ignored on maps < {const.STREETS_MAJOR_ONLY_THRESHOLD}km")
    el_sSmallActive: BoolProperty(name= _("Small Streets"), default=False, description = f"residential, living_street, unclassified, service, footway — ignored on maps < {const.STREETS_PRIMARY_THRESHOLD}km")
    el_oActive: BoolProperty(name=_("Include Ocean"), default=False, description=_("Generate ocean surface cut along the coastline. Experimental"))
    el_oFlip: BoolProperty(name=_("Flip Ocean Side"), default=False, description=_("Flip the cutter normals if the ocean appears on the wrong side"))

    mountain_treshold:IntProperty(name= _("Mountain Threshold"), default = 60, min = 0, max = 100,subtype='PERCENTAGE', description= _("Height Threshold to Color Mountains"))
    cl_thickness: FloatProperty(name= _("Contour Line Thickness"), default = 0.2, description = _("Thickness of the Contour Line"))
    cl_distance: FloatProperty(name= _("Contour Line distance"), default = 2, description = _("Distance between Contour lines"))
    cl_offset: FloatProperty(name= _("Contour Line offset"), default = 0.0, description = _("Offset of the Contour lines"))

    generation_mode: EnumProperty(
        name="Generation Mode",
        items=[
            ('GENERATION', _("Generation"), _("Single GPX file generation")),
            ('MULTI', _("Multi"), _("Chain multiple GPX files")),
            ('TERRAIN', _("Terrain"), _("Generate terrain without GPX")),
        ],
        default='GENERATION',
        update=generation_mode_update
    )# type: ignore

    show_create_settings: BoolProperty(name=_("General Settings"), default=True)

    show_export: BoolProperty(name=_("Export"), default=True)
    disable_auto_export: BoolProperty(name=_("Disable Auto Export"), default=False, description=_("Don't automatically export files after generation"))
    disable_3mf_export: BoolProperty(name=_("Disable 3MF Export"), default=False, description=_("Don't use 3MF format even if the addon is installed"))

    show_stats: BoolProperty(name= _("Additional Info"), default=False)
    show_coloring: BoolProperty(name= _("Elements"), default=False)
    show_chain: BoolProperty(name= _("Multi Generation"), default=False)
    use_multi_generation: BoolProperty(name= _("Multi Generation"), default=False)
    show_map: BoolProperty(name= _("Map"),default=False)
    show_pin: BoolProperty(name= _("Pin"),default=False)
    show_special: BoolProperty(name= _("Special"),default=False)
    show_postProcess: BoolProperty(name= _("Post Process"), default = False)
    show_api: BoolProperty(name= _("API"), default=False)
    show_attribution: BoolProperty(name= _("Attribution"), default = False)
    show_preset: BoolProperty(name= _("Preset"), default=False)

    cityname: StringProperty(name= _("Cityname"), default="Berlin", description = _("Get coordinates of a City"))
    pinLat: FloatProperty(name= _("Latitude"), default = 48.00)
    pinLon: FloatProperty(name= _("Longitude"), default = 8.00)

    mapmode: EnumProperty(
        name="mapmode",
        items=[
            ('FROMPLANE', _("From Selected"), "Generate the Map from a Flat Plane"),
            ('FROMCENTER', _("Center + Radius"), "Generate the Map from a Point coordinate and a Radius"),
            ('2POINTS', _("2 Points"), "Generate the Map from 2 Coordinates")
        ],
        default='FROMPLANE'
    )# type: ignore

    jMapLat: FloatProperty(name="Latitude", default = 49.00)
    jMapLon: FloatProperty(name="Longitude", default = 9.00)
    jMapRadius: FloatProperty(name="Radius im Km", default = 200)

    jMapLat1: FloatProperty(name="Latitude1", default = 48.00)
    jMapLat2: FloatProperty(name="Latitude2", default = 49.00)
    jMapLon1: FloatProperty(name="Longitude1", default = 8.00)
    jMapLon2: FloatProperty(name="Longitude2", default = 9.00)

    
    specialBlendFile: EnumProperty(
        name="Category",
        description= _("Choose what you want to import"),
        items=[
            ("holder.blend", "Map Holder", "Latitudes -60 to 60"),
            ("puzzles.blend","Jigzaw/Sliding Puzzles","global"),
            ("connectors.blend","Map Connectors","Continental USA, Hawaii, parts of Alaska"),
        ],
        default = "puzzles.blend",
        update = utils.loadCollections
        
    )# type: ignore

    # Custom property to store selection
    specialCollectionName: EnumProperty(
        name="specialCollection",
        description= _("Choose a collection from the external .blend"),
        #items=dynamic_specialCollection_items
        items=lambda self, context: const.specialCollection
    )# type: ignore



    #OTHER VARIABLES
    sRunDuration: IntProperty(name="runDuration", default = 0, description = "how long the script was running")
    sAdditionalExtrusion: FloatProperty(name="sAdditionalExtrusion",default = 0)
    sAutoScale: FloatProperty(name="sAutoScale",default = 1)
    sScaleHor: FloatProperty(name="sScaleHor",default = 1, description = "Scale of the Map")
    sMapInKm: FloatProperty(name = "Map Length", default = 0, description = "How much Km are the equivalent of the Map Size")
    sTime_str: StringProperty(name="time_str", default="")
    modelname: StringProperty(name="modelname",default="")
    total_length: FloatProperty(name="total_length",default = 0)
    total_elevation: FloatProperty(name="total_elevation",default = 0)
    total_time: FloatProperty(name="total_time",default = 0)
    average_speed: FloatProperty(name="average_speed",default = 0)
    trail_date: StringProperty(name="trail_date",default = "")

    lowestZ: FloatProperty(name="lowestZ",default = 0)
    highestZ: FloatProperty(name="highestZ",default = 0)
    buggyDataset: BoolProperty(name="buggyDataset",default = 0)
    
    minLat: FloatProperty(name="minLat",default = 0)
    maxLat: FloatProperty(name="maxLat",default = 0)
    minLon: FloatProperty(name="minLon",default = 0)
    maxLon: FloatProperty(name="maxLon",default = 0)

    exportformat: StringProperty(name="exportformat",default = "STL")
    opentopoAdress: StringProperty(name="opentopoAdress", default = "https://api.opentopodata.org/v1/")

    currentMap: PointerProperty(name = "Map object", type = bpy.types.Object)
    currentTrail: PointerProperty(name="Trail object", type = bpy.types.Object)